### PR TITLE
Open taxonomy

### PR DESCRIPTION
**Pull request by Daniel-KM**
Hi,

I added an option to set the taxonomy "open", so, if allowed, the user can update it directly during the edition of an item.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

### CODE REVIEW

**Comment by jajm** [comment]
Hi,

This is a nice feature. Thanks!

Some remarks on the feature itself:

1. The new option is available in Element Types configuration form so if you use the same taxonomy on different elements you could have a different value for this option for the same taxonomy. Wouldn't it be more logical to move the option at the taxonomy level ?
2. The select let the user add more than one term but at most one term will be created on form submit (the one selected). Either the terms should be created automatically (using AJAX) or the select should prevent the user to create more than one term.
3. A taxonomy term is a code associated with a label. The form allows to enter only one value. If the user enters the code that's ok, he will be able to change the label later. But if he enters the label he won't be able to change the code. Rewording `value` to `code` in the form (button, placeholder, option) should be enough to advise the user about what he's supposed to do.
4. The `> Add a new value <` option is not kept at the bottom after a value has been added. Not very important but it looks strange.
5. If you click on `Add Input` button, the added values disappear. I'm not sure we can do something about that though

On the code side:

1. Don't change the plugin's version if it's not needed (database update), and only by incrementing the last number.
2. Please move the block of HTML code into a view script (hookOptionsForm)

**Comment by Daniel-KM** [comment]
Hi,

For feature 1, ok, but to be committed. For 2, this is a possibility. For 3, a second field may be added. For 5, the same issue occurs with Date and in my current needs, the element is single. I don't have time to patch them before two weeks.
For code 1, the scheme version was not specified and when there is a new feature, the number should be incremented, so I use 0.1.1.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by jajm** [comment]
> For feature 1, ok, but to be committed

Does it mean that you're working on it and I should wait before merging this pull request ?

**Comment by Daniel-KM** [comment]
Hi,

I don't work on it currently, but probably in two weeks, if not done before.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by jajm** [comment]
I merged a slightly modified version of this branch, where I removed the plugin's version changes to keep the file history clean.

**Pull request closed without merging**
