### PR TITLE
Path fix

### PR DESCRIPTION
**Pull request by GerZah**
Absolute paths fixed using url("taxonomy"). Also fixed cancel link in delete.php.

### CODE REVIEW

**Comment by jajm** [comment]
It works but you included German translation in your branch.
Could you split commits in separate branches, please ?

**Comment by GerZah** [comment]
Umm. Those are two different commits:
- Patch fix is 9ac99b2
  
  > https://github.com/biblibre/omeka-plugin-Taxonomy/commit/9ac99b2004c7d33060399f78723f70bddb99382e
- German i18n is f4fd32e
  
  > https://github.com/biblibre/omeka-plugin-Taxonomy/commit/f4fd32e70e68466c5b0e87cee16e41d05014e25e

Have I done it wrong? I first committed the path fix and created the 
pull request. I then created the de_DE.po and de_DE.mo and simply 
commited it back to my GitHub repo. It certainly became part of the same 
pull request, but it's two different commits.

_headscratch_

Am 12.06.15 um 13:11 schrieb Julian Maurice:

> It works but you included German translation in your branch.
> Could you split commits in separate branches, please ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biblibre/omeka-plugin-Taxonomy/pull/1#issuecomment-111454871.

## 

Gero Zahn, gerozahn@campus.uni-paderborn.de
University of Paderborn

**Comment by jajm** [comment]
The thing is that git cannot merge commits. It has to be separate branches.

**Comment by GerZah** [comment]
Umm. But I'm not exactly sure how to fix this. Is it possible for me to reverse the language file commit?

Other than that -- just a hunch, but if you're using SourceTree (as I do), you might be able to trigger the merge, but reject the language files during the first run. Then you could carry out a second merge, thus adding the German language in a second commit to your repo. … But that's just a hunch.

**Comment by GerZah** [comment]
Better?

**Comment by jajm** [comment]
Hmm, this adds another commit... but nevermind I'll do this manually, it will be easier

**Comment by GerZah** [comment]
Yes, a third commit is formed by reversing the second one; but the pull request doesn't contain the language files anymore. ;-)

**Comment by jajm** [comment]
Done, thanks!

**Pull request closed without merging**
